[package]
name = "starpad"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.2"
midir = "0.9.1"
inquire = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
